trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'  # Use the appropriate Node.js version
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React App'

  - task: CopyFiles@2
    inputs:
      contents: 'build/**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Build Files'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'react-app'
    displayName: 'Publish Artifact'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: 'build'
      azure_static_web_apps_api_token: $(STATIC_WEB_APPS_API_TOKEN)
    displayName: 'Deploy to Azure Static Web Apps'
